### ISSUE TITLE
How To?

### ISSUE THREAD

**Issue by gvenka008c** [AnsibleShipyard/ansible-mesos#36]
Hi,

Can someone provide a brief explanation of how to use this? Thanks.

Thanks,
Govind

**Comment by anubhavsinha** [comment]
+1 
Need a How to use this playbook in more details. Like an example with a inventory file will be super useful. If the example covers AWS then even better.

**Comment by jolexa** [comment]
This isn't a playbook, this is a role.

So, your specific playbook would look like this
```
---
- hosts: servers
  roles:
    - common
    - { role: ansible-mesos, variable: 'foo' }
```
also, [already documented](https://github.com/AnsibleShipyard/ansible-mesos#configuration)

To duplicate the [ansible documentation](https://docs.ansible.com/ansible/playbooks_roles.html) in this repo seems not appropriate to me.

**Comment by ninthnails** [comment]
Created a wiki page for an example: https://github.com/AnsibleShipyard/ansible-mesos/wiki/Example

**Comment by JasonGiedymin** [comment]
With the added, wiki I'm closing :-)

Thanks @ninthnails and @jolexa!
