### ISSUE TITLE
Setting up SSL?

### ISSUE THREAD

**Issue by koadr** [AnsibleShipyard/ansible-mesos#43]
Will this ansible role support SSL out of the box? I was looking at the documentation [here](http://mesos.apache.org/documentation/latest/ssl/) and it says you have to modify your configure line to enable SSL.

``` bash
../configure --enable-libevent --enable-ssl
```

This of course means you are building it from source, which I don't believe the play does. Is there a way to still use ansible-mesos and enable ssl?

**Comment by JasonGiedymin** [comment]
By default I do not believe the packages we are using have ssl comms enabled. An install mode which is missing from this repo (which at one time may have existed) is to allow a compile mode.

**Comment by JasonGiedymin** [comment]
Enhancement: allow compile mode with configure opts

**Comment by tntC4stl3** [comment]
+1
Is there a plan to add this feature?

**Comment by ernestas-poskus** [comment]
Currently there are no plans for it, feel free to do it
