### ISSUE TITLE
[Question] Is zookeeper necessary packages for this role?

### ISSUE THREAD

**Issue by ryoichitaniguchi** [AnsibleShipyard/ansible-mesos#48]
Hi !
I tried playbook . In the TASK "Install Debian OS packages" (I use Ubuntu), zookeeper* packages sometimes were not installed. With "install_recommends" option, these are installed. entries are missing with_items: ? or can we setup without zookeeper with current configuration of role?  

BTW requirements section in readme says "zookeeper" is necessary package for this role. 
appreciate if any reply.

**Comment by DavidWittman** [comment]
Yes, zookeeper is required for Mesos. You can either use an existing ZK installation or use the [ansible-zookeeper](https://github.com/AnsibleShipyard/ansible-zookeeper) role provided by AnsibleShipyard.
