### ISSUE TITLE
Cannot start agent due to "Failed to perform recovery: Incompatible agent info detected."

### ISSUE THREAD

**Issue by veger** [AnsibleShipyard/ansible-mesos#65]
Sometimes mesos slaves do not want to start :

```
Failed to perform recovery: Incompatible agent info detected.

<lots of JSON>

To remedy this do as follows:
Step 1: rm -f /var/mesos/meta/slaves/latest
        This ensures agent doesn't recover old live executors.
Step 2: Restart the agent.
```

(from journalctl)

After removing the _latest_ directory as suggested, the agent starts again.

I believe it is due to http://www.flexthinker.com/2015/09/reconfiguring-mesos-agents-slaves-with-new-resources/

It is possible to detect changes in the resources (one of the templates?) and automatically remove the _latest_ directory?
Additionally, an variable can be introduced to enable/disable this behavior

**Comment by ernestas-poskus** [comment]
Strange haven't encountered this behavior yet I am using ```mesos_version: '1.0.1'```.  Provided link ~ year old maybe this was fixed in later versions. What version you are using ?

**Comment by veger** [comment]
I am also using version 1.0.1.
When I change the configuration of an _existing_ slave, the issue arises.

Last change I did (which triggered the issue), was changing the resources (ports):

```
mesos_slave_additional_configs:
- name: RESOURCES
  value: '"ports:[{{ mesos_slave_resource_port_range }}]"'
```

But it also happen when I change the `ATTRIBUTES` using the `mesos_slave_additional_configs` variable.

**Comment by lhoss** [comment]
We have the same 'issue' 
that happens in a reproducable way, for ex. when updating the `MESOS_RESOURCES` variable in:
```
TASK [teralytics.mesos : Mesos Slave config file] ******************************
...
--- before: /etc/default/mesos-slave
+++ after: dynamically generated
@@ -8,5 +8,5 @@
 # Additional configs
 export MESOS_HADOOP_HOME=/usr/local/tl/hadoop
-export MESOS_RESOURCES="cpus(*):0; mem(*):0; disk(*):0; ports(*):[20001-31000]; cpus(marathon_role):30; mem(marathon_role):100000; disk(marathon_role):20000; ports(marathon_role):[23-20000];"
+export MESOS_RESOURCES="cpus(*):30; mem(*):100000; disk(*):20000;ports:[23-20000];"
 export MESOS_ISOLATION=cgroups/cpu,cgroups/mem
```

As an easy fix, I'ld propose to add an (optional) feature (by enabling a variable like `mesos_agent_meta_cleanup`)
that removes this `/var/mesos/meta/slaves/latest` (before the restart handler takes action).
I could submit a PR

**Comment by ernestas-poskus** [comment]
> As an easy fix, I'ld propose to add an (optional) feature (by enabling a variable like mesos_agent_meta_cleanup)

sounds like a good option

**Comment by lhoss** [comment]
PR ready for review -^
... and already used on 1 ubuntu(14.04) node with mesos v0.28.2 successfully (ps: also tested with feature disabled)

**Comment by lhoss** [comment]
@ernestas-poskus @veger  can we close (PR was merged) ?

**Comment by ernestas-poskus** [comment]
We do, reopen if not.

**Comment by veger** [comment]
thanks for the fix, I'll try the new release soon!
